# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    phpmyadmin.repository.generic:
        abstract: true
        class: PhpMyAdminBundle\Repository\GenericRepository
        arguments: ['@doctrine.orm.entity_manager']
        calls:
            - [setPaginator, ["@knp_paginator"]]

    phpmyadmin.repository.tables:
        parent: phpmyadmin.repository.generic
        class: PhpMyAdminBundle\Repository\TablesRepository
